### ISSUE TITLE
Getting an issue after executing the main file

### ISSUE THREAD

**Issue by xofax** [Sxvxgee/SwiftSnipe#1]
hi, i am getting an error, i have also attached my config file to show if i have made a mistake or not.

![Notepad_my07Bqlt1z](https://github.com/Sxvxgee/SwiftSnipe/assets/71617943/fe373910-f696-4a08-9527-c5b2dc6bf731)
![WindowsTerminal_6brmhQnl5E](https://github.com/Sxvxgee/SwiftSnipe/assets/71617943/41a5e81b-cfe8-4e05-9d5a-e1997f6bd3f8)

**Comment by theAbdoSabbagh** [comment]
Hi, this error is because of the config file. JSON is very senestive, any missing or extra character in the wrong way can break it, like any other format. To fix your code, add a comma on the end of the third line, right after the closing square bracket, the line that has the word "xofa" to be specific. This should fix it.

Thanks for using SwiftSnipe btw! If you have suggestions for the project please do let me know! And if you haven't already, consider starring the project to help making it more visible to other people!

**Comment by xofax** [comment]
thank you for replying, i have modified it but i am still getting the same error
![Notepad_RleZ9n7Qqj](https://github.com/Sxvxgee/SwiftSnipe/assets/71617943/6fc8f2ac-b1ba-4cad-9106-15b5cf68bf19)

**Comment by theAbdoSabbagh** [comment]
Could you remove the sensitive information you're blurring then send me the config file contents so I can test myself? I can just open my IDE with that file and find errors inside of it instead of manually checking.

**Comment by xofax** [comment]
`{
  "namelists": {
	"xofa": ["zzz", "zzz"],
	"milfbaiter": ["zzz", "zzz"]
},
  "accounts": [
	{	
		"token": "zzz",
		"namelists": ["zzz"]
},
],
  "delays": {
    "nameRetry": 300,
    "retry": 3600
  },
  "webhook": {
    "enabled": false,
    "sendFailures": false,
    "pingRoleId": "",
    "url": ""
  }
}`

**Comment by theAbdoSabbagh** [comment]
```json
{
    "namelists": {
        "xofa": [
            "zzz",
            "zzz"
        ],
        "milfbaiter": [
            "zzz",
            "zzz"
        ]
    },
    "accounts": [
        {
            "token": "zzz",
            "namelists": [
                "zzz"
            ]
        }
    ],
    "delays": {
        "nameRetry": 300,
        "retry": 3600
    },
    "webhook": {
        "enabled": false,
        "sendFailures": false,
        "pingRoleId": "",
        "url": ""
    }
}
```

This is the fixed JSON data. Should fix your error now.

**Comment by xofax** [comment]
thanks man, you rock! had the repo starred already haha

**Comment by theAbdoSabbagh** [comment]
Glad to hear that! If you need any further assistance don't hesitate to open another issue!
